"""
fetch_fonts.py — self-host the site's Google Fonts (latin subset, woff2) in assets/fonts/
and write assets/fonts/fonts.css. Also downloads TTF copies to the scratch folder for
generating Open Graph images with Pillow (tools/make_og.py).

Run once (or whenever the font set changes):  python tools/fetch_fonts.py
"""
from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "assets" / "fonts"
TTF_DIR = ROOT / "tools" / ".fonts-ttf"

FAMILIES = (
    "family=Cormorant+Garamond:ital,wght@0,500;0,600;0,700;1,400;1,500"
    "&family=Outfit:wght@300;400;500;600;700"
    "&family=Fira+Code:wght@400;500"
)
CSS_URL = f"https://fonts.googleapis.com/css2?{FAMILIES}&display=swap"

UA_WOFF2 = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
            "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")
UA_TTF = "Mozilla/4.0"          # legacy UA → Google serves TTF


def fetch(url: str, ua: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": ua})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def slug(family: str) -> str:
    return family.lower().replace(" ", "-")


def main() -> None:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    TTF_DIR.mkdir(parents=True, exist_ok=True)

    css = fetch(CSS_URL, UA_WOFF2).decode("utf-8")
    blocks = re.findall(r"/\*\s*(\w[\w-]*)\s*\*/\s*(@font-face\s*\{[^}]*\})", css)
    out_css = ["/* Self-hosted Google Fonts — generated by tools/fetch_fonts.py (latin subset) */"]
    n = 0
    for subset, block in blocks:
        if subset != "latin":
            continue
        fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        style = re.search(r"font-style:\s*(\w+)", block).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
        url = re.search(r"url\(([^)]+\.woff2)\)", block).group(1)
        urange = re.search(r"unicode-range:\s*([^;]+);", block).group(1)
        fname = f"{slug(fam)}-{weight}{'-italic' if style == 'italic' else ''}.woff2"
        target = FONT_DIR / fname
        if not target.exists():
            target.write_bytes(fetch(url, UA_WOFF2))
        n += 1
        out_css.append(
            "@font-face{font-family:'%s';font-style:%s;font-weight:%s;font-display:swap;"
            "src:url('%s') format('woff2');unicode-range:%s;}" % (fam, style, weight, fname, urange)
        )
        print(f"  {fname}  {target.stat().st_size // 1024} KB")
    (FONT_DIR / "fonts.css").write_text("\n".join(out_css) + "\n", encoding="utf-8")
    print(f"{n} font files -> {FONT_DIR.relative_to(ROOT)}/fonts.css")

    # TTFs for Pillow (OG image rendering) — Outfit 600 & Cormorant 600 are enough
    ttf_css = fetch("https://fonts.googleapis.com/css?family=Outfit:400,600|Cormorant+Garamond:600,700", UA_TTF).decode()
    for m in re.finditer(r"font-family:\s*'([^']+)';\s*font-style:\s*\w+;\s*font-weight:\s*(\d+);\s*src:.*?url\(([^)]+\.ttf)\)", ttf_css, re.S):
        fam, weight, url = m.groups()
        target = TTF_DIR / f"{slug(fam)}-{weight}.ttf"
        if not target.exists():
            target.write_bytes(fetch(url, UA_TTF))
        print(f"  ttf: {target.name}")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:  # network failures should be loud but not fatal for the build
        print("fetch_fonts failed:", e, file=sys.stderr)
        sys.exit(1)
